config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'sessions/new'
  get 'users/new'
  get 'pages/index'
  root 'pages#index'
  get 'pages/help'

  resources :users
  resources :topics

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :construction_work_contents, presence: true
  validates :drawing, presence: true
  validates :address, presence: true
  validates :suitable_time, presence: true
  validates :budget, presence: true
  validates :important_think, presence: true

  belongs_to :user

  mount_uploader :construction_site_picture, ImageUploader
  mount_uploader :drawing, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true,
             length: { maximum: 15 }

  validates :phone_number, presence: true
  validates :bd,presence: true
  validates :password,format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

  has_secure_password

  has_many :topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(phone_number: params[:session][:phone_number])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
      log_out
      redirect_to root_url, info: 'ログアウトしました'
  end
    private
    def log_in(user)
      session[:user_id] = user.id
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end

   def login_phone_number_params
     params.require(:session).permit(:phone_number)
   end
   def login_password_params
     params.require(:session).permit(:password)
   end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
      @topics = Topic.all
  end


  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description,:construction_work_contents,:occupation,:drawing,:construction_site_picture,:address,:suitable_time,:budget,:important_think)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  if @user.save
    redirect_to root_path,success: '登録が完了しました'
  else
    flash.now[:danger] = "登録に失敗しました"
    render :new
  end
  end

  private
 def user_params
   params.require(:user).permit(:name, :phone_number,:bd,:password, :password_confirmation)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Const</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to "#" do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag 'icons/camera.png' %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>

    <script>
      $(function(){
        $('.alert').fadeOut(3000);
      });
    </script>

  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページですyo</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">WE DO NOT LET YOU DOWN</h1>
    <h2 class="text-white">コンストは建築業界に革命を起こします。</h2>
    <p> 充分に合理的ではない建築業界を変えたいために生まれた</p>
    <p> 建築関係の仕事をしてる人と依頼したい人を直接マッチングさせる</p>
    <p> なおかつ誰でも使い熟せて簡単に工事を個人に依頼できて</p>
    <p>信頼性、操作性、価格帯、創造性など全てにおいて新しいサービスです </p>
    <p>　　　　</p>
    <p>　　　　</p>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign up', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', login_path,class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.construction_site_picture.url %>
            <%= image_tag topic.drawing.url %>
            <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">　工事内容：<%= topic.construction_work_contents %></p>
          　<p class="topic-text">　現場住所： <%= topic.address %></p>
            <p class="topic-text">　希望工期： <%= topic.suitable_time %></p>
            <p class="topic-text">　予算：   <%= topic.budget %>
            <p class="topic-text">　重要視項目：   <%= topic.important_think %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">見積り</h1>
        <%= form_for @topic do |f| %>

          <div class="form-group">
            <%= f.label :工事内容 %>
            <%= f.text_area :construction_work_contents, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :必要職種 %>
            <%= f.text_area :occupation, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :現場の写真 %>
            <%= f.file_field :construction_site_picture %>
          </div>

          <div class="form-group">
            <%= f.label :図面 %>
            <%= f.file_field :drawing%>
          </div>

          <div class="form-group">
            <%= f.label :現場の住所 %>
            <%= f.text_area :address, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :希望工期 %>
            <%= f.text_area :suitable_time, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :予算 %>
            <%= f.text_area :budget, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :重要視項目 %>
            <%= f.text_area :important_think, class: 'form-control' %>
          </div>





          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :phone_number, class: 'text-white' %>
            <%= f.text_field :phone_number, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Birthday_例19940608, class: 'text-white' %>
            <%= f.text_field :bd, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :Password_Confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>


          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', 'login_path',class: 'text-white' %>
      </div>
    </div>
  </div>
</div>